# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_check_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('code', models.UUIDField(null=True)),
                ('hierachy', models.IntegerField(default=0)),
            ],
        ),
    ]
